- name: Ensure necessary packages are installed
  become: true
  ansible.builtin.package:
    name:
      - awesome
      - blueman
      - i3lock
      - lxqt-config
      - lxqt-session
      - network-manager-gnome
      - playerctl
      - xss-lock
    state: present
