"$schema" = 'https://starship.rs/config-schema.json'

[c]
disabled = true

[direnv]
disabled = false

allowed_msg = "a"
not_allowed_msg = "na"

loaded_msg = "l"
unloaded_msg = "nl"

[docker_context]
only_with_files = false

[git_branch]
symbol = "🌿 "

[git_state]
cherry_pick = '[🍒 PICKING](bold red)'

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

conflicted = "${count}🤨"
modified = "${count}👀"
stashed = "${count}📦"
staged = "${count}😌"
untracked = "${count}🤷"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format ="([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[golang]
disabled = true

[memory_usage]
disabled = false

[nix_shell]
format = 'via [$symbol$state( \($name\))]($style) '
impure_msg = "🪨"
pure_msg = "💎"
symbol = "❄️ "

[python]
detect_extensions = []

[shell]
disabled = false
fish_indicator = '󰈺 '

[status]
disabled = false
format = '[$symbol $status]($style) '

[typst]
disabled = true
