- name: Check Latest Zoxide
  uri:
    url: https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest
    return_content: true
  register: zoxide_latest

- name: "Download Zoxide {{ zoxide_latest.json.tag_name }}"
  loop: "{{ zoxide_latest.json.assets }}"
  when: "'amd64.deb' in item.name"
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.XDG_CACHE_HOME }}/dotfiles/zoxide.deb"
  no_log: true

- name: "Install Zoxide"
  apt:
    deb: "{{ ansible_env.XDG_CACHE_HOME }}/dotfiles/zoxide.deb"
  become: true
