# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: foobar
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: foobar
    hooks:
    -   id: mypy
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: foobar
#     hooks:
#     -   id: ruff-format
