#!/usr/bin/env bash

set -euo pipefail

if [ -x "./.git/hooks/pre-commit" ]; then
    exec ./.git/hooks/pre-commit;
fi

if [ -e "./.pre-commit-config.yaml" ]; then
    echo -e "\e[0;33mA .pre-commit-config.yaml file exists, but there is no pre-commit hook in your repository.\e[0m"
    echo -e "\e[0;33mDid you forget to run \`pre-commit install\`?\e[0m"
    exit 1;
fi

